### ISSUE TITLE
Question regarding the polling and maximum count value

### ISSUE THREAD

**Issue by yuang-chen** [aliireza/slice-aware#2]
Dear Alireza,

Your code is very elegant. However, I have difficulty in understanding the details since I have no experience in security. 
Can you please explain a bit: 
1. why the `polling` function is just a repetition of `_mm_clflush`?
2. why the maximum value of CHA-CBO counter is selected for deciding the index of slice?

Your prompt reply will be appreciated!

Best Regards,
YuAng

**Comment by aliireza** [comment]
Hi YuAng,

I suggest you read my paper (https://people.kth.se/~dejanko/documents/publications/slice-aware-eurosys19.pdf) to have a better understanding of the algorithm. However, I will do my best to explain everything concisely here.

In Intel processors, LLC is divided into multiple "slices," each of which is equipped with some performance counters, called CBO/CHA. For instance, each CBO/CHA can count the number of accesses to an LLC slice.

To find the mapping between a cache line and LLC slices, (i) we access the cache line many times and then (ii) compare the number of accesses to different LLC slices counted by different CBO/CHA counters. 

1) `polling` function performs the first part by accessing a cache line's address multiple times (e.g., 750 times), but we have to make sure that the address is being loaded to LLC every time. Therefore, I use the `_mm_clflush` function (see https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_clflush&expand=678) to invalidate the cache lines in the whole cache hierarchy to make sure that the cache lines are loaded into LLC for every access. 

2) Although we access one address, there are still other variables that could be loaded in the LLC, adding some noise in the CBO/CHA counters. Therefore, I choose the CBO with the maximum number of accesses as the slice associated with the polled address. I think the security paper that suggested this method (https://cmaurice.fr/pdf/raid15_maurice.pdf) polled an address 1000 times, but 750 was enough in my testbed. You may need to fine-tune that. 

I hope I have answered your questions.

Please let me know if you have more questions.

Cheers,
Alireza

**Comment by yuang-chen** [comment]
Dear Alireza,

Thanks so much for you reply. It takes a few days for me to digest the recommended papers.  Combining with your explanation, I have a much better understanding towards the code now.

Still, some minor questions exist in my head. 

For the Haswell, why the number of memory chunk to fit in LLC is 16 (2 * L2_WAYS), instead of 20 (the set asso. of LLC) 
```
/* Memory Chunks -> Fit in LLC */
	unsigned long long nTotalChunks=2*L2_WAYS;  // 16
```
In your paper, it is mentioned that "In our test application, only twenty cache lines have been
selected because of the set-associativity of this processor’s LLC." Does the `nTotalChunks ` refer to the testing cache lines in this context?

Again, thanks so much for your help.

Best Regards,
YuAng

**Comment by aliireza** [comment]
Yes, it does. I guess I changed it to 16 (instead of 20) when I published the source code. 

If you look at the code here: https://github.com/aliireza/slice-aware/blob/master/apps/L3_access_measurement.c

1) It allocates `nTotalChunks` cache lines mapped to a specific LLC slice with the same L1/L2/L3-slice index.
2) It initializes the cache lines and flushes them from the cache hierarchy.
3) It accesses all of the allocated cache lines to ensure that there are loaded into the cache.  
4) It accesses some of the already loaded cache lines that are loaded into the LLC, but not L1/L2 to measure the access time to an LLC slice.

What you are asking is related to the third+fourth steps, in which we have to make sure that we have some cache lines that are _most probably_ available in LLC (but not L1/L2) - let's call this `our measurement scenario`. 

To create this scenario, we have to learn how does the cache hierarchy works. 

In the Haswell processor that I used (i.e., Intel Xeon-E5-2667-v3), we have an 8-way set associative L1 cache + an 8-way set associative L2 cache. Since the cache hierarchy is inclusive in Haswell, if we load something from memory, it will be available in all cache levels (i.e., L1+L2+LLC). 

If we select any number of cache lines `20>x>8` mapped to the same cache indexes at all levels, we could create the `measurement scenario`. 

For instance, let's assume 16 cache lines (i.e., `nTotalChunks=16`). 

If we access all 16 cache lines in step 3, the **first** eight cache lines are replaced in L1/L2 with the **second** eight cache lines since the cache associativity of L1/L2 is only 8. See: https://github.com/aliireza/slice-aware/blob/f3d2860e4ee694838620a166c23429050b36df05/apps/L3_access_measurement.c#L155

After this step, our specific LLC slice contains the first 8 cache lines (previously evicted from L1/L2), whereas L1/L2 contains the second 8 cache lines. Therefore, if we access the **first** 8 cache lines, most probably they will be loaded from LLC into L1, and we can measure our desired access time. See: https://github.com/aliireza/slice-aware/blob/f3d2860e4ee694838620a166c23429050b36df05/apps/L3_access_measurement.c#L174

Note that these are just speculations because we might have other variables that could affect the placements in the cache hierarchy. To mitigate this, I repeat these measurements multiple times and use boxplot to look at their distribution, see Figure 5 in my paper.

I hope I have not confused you :)

Cheers,
Alireza

**Comment by yuang-chen** [comment]
Dear Alireza,

Your explanation is crystal clear. And the idea behind it is really enlightening to my research.

Now I fully understand how the `L3_access` and `mapping_finder` works.  

However, I am a bit confused by the `poormans_multicore_**`. My understanding is:  These two programs (slice and no_slice) read or write the memory/cache according to the access pattern file from, e.g., PROJECT/workload/sample/Zipf-s0.99/ZF-size-32KB-***.

I tried to execute the program but failed:
![image](https://user-images.githubusercontent.com/26096407/94634572-00509b80-0303-11eb-845e-189bc2444296.png)

It is really weird since I can run the `L3_access` and `mapping_finder`  without encountering any problems. Can you please provide your insights into this issue?

In addition, for the Skylake model Intel Xeon Gold 6134, the number of LLC slices, as presented in your paper, is 18, while the number of core is 8. The mismatch of numbers goes against my intuition.  The connection between LLC slices and cores would be a mess.

I cannot find official Intel documents that tells the exact number of LLC slices of a processor. However, many online resources, e.g., [link1](https://en.wikichip.org/wiki/intel/microarchitectures/skylake_(server)), indicts by figures that a LLC slice is mapped one-to-one to a single core. [Link2](https://www.nas.nasa.gov/hecc/support/kb/skylake-processors_550.html), claims that a 20-core Xeon Gold 6148 (Skylake) has 10*2 LLC slices in each socket. 

Therefore, can you please let me know how did you decide the number of LLC slices in your Intel Xeon Gold 6134? 

Thank you in advance!


Best Regards,
YuAng

**Comment by aliireza** [comment]
Great! I am happy that our work is useful for your research! 

---------------------------------------------------------------

Exactly! `poormans_multicore_*` allocate memories and then read/write them. The error that you get is related to `create_buffer` function: https://github.com/aliireza/slice-aware/blob/f3d2860e4ee694838620a166c23429050b36df05/lib/memory-utils.c#L45

With the default parameters, it allocates 1-GB hugepages, which requires hugepage reservations at boot time. I guess you have not reserved any or enough hugepages, which is causing this error. `create_buffer` needs 8-GB every time you call it (per core), as it has to hand-pick cache lines mapped to a specific LLC slice. See: https://github.com/aliireza/slice-aware/blob/f3d2860e4ee694838620a166c23429050b36df05/lib/memory-utils.c#L22

**You could change my code to make it more memory efficient, i.e., allocate once and distribute cache lines among different arrays, instead of allocating 8 times (for 8 cores) and handpick the cache lines independently.**

There are two ways to fix this:

1) Comment `#define USE_HUGEPAGE` https://github.com/aliireza/slice-aware/blob/f3d2860e4ee694838620a166c23429050b36df05/lib/memory-utils.c#L20
After commenting this, `mmap` should use 4-kB pages to allocate memory. 

2) Reserve hugepages via GRUB as follows (or via this link: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/sect-red_hat_enterprise_linux-performance_tuning_guide-memory-configuring-huge-pages).

- `sudo vim /etc/default/grub`
- Add something like `default_hugepagesz=1GB hugepagesz=1G hugepages=32` to `GRUB_CMDLINE_LINUX`. Note that you -should set the number of hugepages (i.e., `hugepages=32`) based on your available memory. 
- `sudo update-grub` 
- Reboot
- You can check the number of hugepages via `cat /proc/meminfo | grep HugePages`

I suggest you check the other parameters that I have used for `FLAGS`: https://github.com/aliireza/slice-aware/blob/f3d2860e4ee694838620a166c23429050b36df05/lib/memory-utils.c#L34

I have other configurations in grub (e.g., isolated some cores to improve measurements accuracy); you can check here for more details: https://github.com/aliireza/ddio-bench/blob/master/TESTBED.md#other-configurations



---------------------------------------------------------------

Yes! Skylake is a bit complicated because of the mismatch between the LLC slices <-> cores and the non-inclusive cache hierarchy. 

You can calculate the number of LLC slices by dividing the LLC size by the size of an LLC slice (i.e., 1.375 MB: see [here](https://software.intel.com/content/www/us/en/develop/articles/intel-xeon-processor-scalable-family-technical-overview.html)), For example, Intel Xeon Gold 6134 has 24.75 MB LLC, i.e., 24.75 MB / 1.375 MB = 18 LLC slices). 

According to the [link_1](https://en.wikichip.org/wiki/intel/microarchitectures/skylake_(server)), there are three different configurations (search for `LCC SoC` in the page) : (i) 10 cores/LLC slices, (ii) 18 cores/LLC slices, and (iii) 28 cores/LLC slices. 

I am not an expert in either chip fabrication or computer architecture, but I think some of the cores may not provide the expected performance due to the fabrication process. Therefore, they handpick the ones that pass some tests, which leaves us with CPUs that have fewer cores than the number of LLC slices (e.g., Intel Xeon Gold 6134). The location of the cores may differ in each CPU. Consequently, if you want to use slice-aware memory management on SkyLake processors, you have to profile them and find the optimal mapping between slices <-> cores. 

John Mccalpin (aka Dr. Bandwidth) has spent some time on this topic. You can find more info in the following slides:

1) https://www.ixpug.org/components/com_solutionlibrary/assets/documents/1538092216-IXPUG_Fall_Conf_2018_paper_20%20-%20John%20McCalpin.pdf

2) https://www.ixpug.org/resources/download/mccalpin-address-hashing-sc18bof


Cheers,
Alireza

**Comment by yuang-chen** [comment]
Dear Alireza,

Thanks for your detailed reply!

---
Indeed, the error results from `create_buffer`. I have allocated 8G hugepage for my machine, thus I can play around with L3_access without any trouble because it uses only one core. However, when running into multicore scenarios such as the `poormans_multicore_*`,  where multi-threads demand significantly more hugepages, the shortage of hugepage resource causes the program to be stopped.

> With the default parameters, it allocates 1-GB hugepages, which requires hugepage reservations at boot time. I guess you have not reserved any or enough hugepages, which is causing this error. `create_buffer `needs 8-GB every time you call it (per core), as it has to hand-pick cache lines mapped to a specific LLC slice

Let me try to interpret your words above.  For each core, 8 G hupepages are needed, but only 1/8 of them are utilized for the preferred LLC slice. It is quite inefficient because 7 G hugepages are not used at all! As for the multicore case, e.g., 8 cores, we need to allocate 64 G hupages, even though only 8G of them are in fact used. 

Unfortunately the memory size of my machine is 64 G. Therefore I have to 
1. change the code to make use of every Byte in the hugepage. So 8G hugepages would be enough even for multi-thread applications. 
2. or, use normal 4-kB pages, which might slow down the processing of the applications because of the frequent page table inquiries. 

Am I comprehending this correctly?

---

The information and resources you provided relating to Skylake is truly interesting. I am digging into it right now. 

---

Endless gratitude for your kind help,

YuAng

**Comment by aliireza** [comment]
Yes, you got it right! 

I think the best option would be to change the code a bit; it is not too complicated ;)

I believe you may need a bit more than 8 GB (e.g., 9-10 GB), as the hash function is not 100% uniform (i.e., some LLC slices may be used more frequently in a specific memory address space). 

You're welcome. I am happy to help :)

Cheers,
Alireza

**Comment by yuang-chen** [comment]
Dear Alireza,

Great! My issue is settled. Thanks for your patience and explanation!


Best Regards,
YuAng
